language: python
python:
    - "2.7"

install:
    - export DATABASE_URL='sqlite:///travis.sqlite3'
    - pip install -r requirements.txt
script:
    - make syncdb migrate
    - python manage.py test
